/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_sz_jvm_jdk_Threads */

#ifndef _Included_com_sz_jvm_jdk_Threads
#define _Included_com_sz_jvm_jdk_Threads
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_sz_jvm_jdk_Threads
 * Method:    createVM
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_sz_jvm_jdk_Threads_createVM
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
